version: '3.11'

services:
  metabase-url-server:
    build: .
    ports:
      - "7070:7070"
    environment:
      - TOKEN_EXPIRATION_MINUTES=${TOKEN_EXPIRATION_MINUTES:-30}
    volumes:
      - ./logs:/app/logs
      - ./conf:/app/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
